apiVersion: v1
kind: Secret
metadata:
  name: leave-form-v2-file-secret
  namespace: leave-form-v2-ns
type: Opaque
data:
  public.pem: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFSytZcXBpdHM1UCswaDZ4MmRnZHBKOHRrWi82dQpLdlZUTDZmaUxWMHg3Um8wME9nYVF5bHVPekk1VE5IdVVFSGtLaVZzYm9SOTFreU1GY0pVb3NJejZRPT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
  private.pem: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZzFacjNMdEtyRk9iWGRuMkIKNEdoSjBrak1BT1Y3dzc3bVd4TEhzZnRMNkFLaFJBTkNBQVFyNWlxbUsyemsvN1NIckhaMkIya255MlJuL3E0cQo5Vk12cCtJdFhUSHRHalRRNkJwREtXNDdNamxNMGU1UVFlUXFKV3h1aEgzV1RJd1Z3bFNpd2pQcAotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==

